// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *HeaderContent → Palabras*
 */
export interface BodyDocumentDataPalabrasItem {
  /**
   * Palabra field in *HeaderContent → Palabras*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: body.palabras[].palabra
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  palabra: prismic.KeyTextField;
}

/**
 * Content for HeaderContent documents
 */
interface BodyDocumentData {
  /**
   * herogif field in *HeaderContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: body.herogif
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herogif: prismic.ImageField<never>;

  /**
   * Title header field in *HeaderContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: body.title_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_header: prismic.KeyTextField;

  /**
   * Palabras field in *HeaderContent*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: body.palabras[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  palabras: prismic.GroupField<Simplify<BodyDocumentDataPalabrasItem>>;

  /**
   * Text header field in *HeaderContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: body.text_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_header: prismic.KeyTextField;
}

/**
 * HeaderContent document from Prismic
 *
 * - **API ID**: `body`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BodyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BodyDocumentData>, "body", Lang>;

/**
 * Item in *BodyContent → Group one*
 */
export interface BodycontentDocumentDataGroupOneItem {
  /**
   * Titulo field in *BodyContent → Group one*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_one[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Contenido field in *BodyContent → Group one*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_one[].contenido
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contenido: prismic.KeyTextField;

  /**
   * Texto abajo field in *BodyContent → Group one*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_one[].texto_abajo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto_abajo: prismic.KeyTextField;
}

/**
 * Item in *BodyContent → Group two*
 */
export interface BodycontentDocumentDataGroupTwoItem {
  /**
   * Titulo field in *BodyContent → Group two*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_two[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Contenido field in *BodyContent → Group two*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_two[].contenido
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contenido: prismic.KeyTextField;
}

/**
 * Item in *BodyContent → Group three*
 */
export interface BodycontentDocumentDataGroupThreeItem {
  /**
   * Contenido field in *BodyContent → Group three*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_three[].contenido
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contenido: prismic.KeyTextField;

  /**
   * Nombre field in *BodyContent → Group three*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_three[].nombre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;

  /**
   * Posicion field in *BodyContent → Group three*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_three[].posicion
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  posicion: prismic.KeyTextField;
}

/**
 * Item in *BodyContent → Group four*
 */
export interface BodycontentDocumentDataGroupFourItem {
  /**
   * Titulo field in *BodyContent → Group four*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_four[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Contenido imagen uno field in *BodyContent → Group four*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_four[].contenido_imagen_uno
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contenido_imagen_uno: prismic.KeyTextField;

  /**
   * Contenido imagen dos field in *BodyContent → Group four*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_four[].contenido_imagen_dos
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contenido_imagen_dos: prismic.KeyTextField;

  /**
   * Contenido imagen tres field in *BodyContent → Group four*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_four[].contenido_imagen_tres
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contenido_imagen_tres: prismic.KeyTextField;

  /**
   * Texto abajo field in *BodyContent → Group four*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_four[].texto_abajo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto_abajo: prismic.KeyTextField;
}

/**
 * Item in *BodyContent → Group five*
 */
export interface BodycontentDocumentDataGroupFiveItem {
  /**
   * Titulo field in *BodyContent → Group five*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_five[].titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * BotonLink field in *BodyContent → Group five*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_five[].botonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  botonlink: prismic.LinkField;

  /**
   * BotonTexto field in *BodyContent → Group five*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_five[].botontexto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botontexto: prismic.KeyTextField;
}

/**
 * Content for BodyContent documents
 */
interface BodycontentDocumentData {
  /**
   * Scroll image one field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.scrollimageone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  scrollimageone: prismic.ImageField<never>;

  /**
   * Text image one  field in *BodyContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.text_image_one
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_image_one: prismic.KeyTextField;

  /**
   * Scroll image two field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.scroll_image_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  scroll_image_two: prismic.ImageField<never>;

  /**
   * Text image two field in *BodyContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.text_image_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_image_two: prismic.KeyTextField;

  /**
   * Scroll image three field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.scroll_image_three
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  scroll_image_three: prismic.ImageField<never>;

  /**
   * Text image three field in *BodyContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.text_image_three
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_image_three: prismic.KeyTextField;

  /**
   * Scroll image four field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.scroll_image_four
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  scroll_image_four: prismic.ImageField<never>;

  /**
   * Text image four field in *BodyContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.text_image_four
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_image_four: prismic.KeyTextField;

  /**
   * Scroll image five field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.scroll_image_five
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  scroll_image_five: prismic.ImageField<never>;

  /**
   * Text image five field in *BodyContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.text_image_five
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_image_five: prismic.KeyTextField;

  /**
   * Scroll image six field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.scroll_image_six
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  scroll_image_six: prismic.ImageField<never>;

  /**
   * Text image six field in *BodyContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.text_image_six
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_image_six: prismic.KeyTextField;

  /**
   * Scroll image seven field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.scroll_image_seven
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  scroll_image_seven: prismic.ImageField<never>;

  /**
   * Text image seven field in *BodyContent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.text_image_seven
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_image_seven: prismic.KeyTextField;

  /**
   * Group one field in *BodyContent*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_one[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_one: prismic.GroupField<Simplify<BodycontentDocumentDataGroupOneItem>>;

  /**
   * Group two field in *BodyContent*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_two[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_two: prismic.GroupField<Simplify<BodycontentDocumentDataGroupTwoItem>>;

  /**
   * Group three field in *BodyContent*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_three[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_three: prismic.GroupField<
    Simplify<BodycontentDocumentDataGroupThreeItem>
  >;

  /**
   * Group four field in *BodyContent*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_four[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_four: prismic.GroupField<
    Simplify<BodycontentDocumentDataGroupFourItem>
  >;

  /**
   * Group five field in *BodyContent*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.group_five[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_five: prismic.GroupField<
    Simplify<BodycontentDocumentDataGroupFiveItem>
  >;

  /**
   * Certificacion uno field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.certificacion_uno
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  certificacion_uno: prismic.ImageField<never>;

  /**
   * Certificacion dos field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.certificacion_dos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  certificacion_dos: prismic.ImageField<never>;

  /**
   * Certificación tres field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.certificacion_tres
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  certificacion_tres: prismic.ImageField<never>;

  /**
   * Logo uno field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.logo_uno
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_uno: prismic.ImageField<never>;

  /**
   * Logo dos field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.logo_dos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_dos: prismic.ImageField<never>;

  /**
   * Logo tres field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.logo_tres
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_tres: prismic.ImageField<never>;

  /**
   * Avatar field in *BodyContent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bodycontent.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;
}

/**
 * BodyContent document from Prismic
 *
 * - **API ID**: `bodycontent`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BodycontentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BodycontentDocumentData>,
    "bodycontent",
    Lang
  >;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Imagen footer field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.imagen_footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagen_footer: prismic.ImageField<never>;

  /**
   * Direccion field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.direccion
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  direccion: prismic.KeyTextField;

  /**
   * Footer link uno field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_links: prismic.KeyTextField;

  /**
   * Footer link dos field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_link_dos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_link_dos: prismic.KeyTextField;

  /**
   * Footer link tres field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_link_tres
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_link_tres: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Navbar documents
 */
interface NavbarDocumentData {
  /**
   * Logo field in *Navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Boton Link field in *Navbar*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.boton_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  boton_link: prismic.LinkField;

  /**
   * BotonText field in *Navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.botontext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  botontext: prismic.KeyTextField;
}

/**
 * Navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

export type AllDocumentTypes =
  | BodyDocument
  | BodycontentDocument
  | FooterDocument
  | NavbarDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BodyDocument,
      BodyDocumentData,
      BodyDocumentDataPalabrasItem,
      BodycontentDocument,
      BodycontentDocumentData,
      BodycontentDocumentDataGroupOneItem,
      BodycontentDocumentDataGroupTwoItem,
      BodycontentDocumentDataGroupThreeItem,
      BodycontentDocumentDataGroupFourItem,
      BodycontentDocumentDataGroupFiveItem,
      FooterDocument,
      FooterDocumentData,
      NavbarDocument,
      NavbarDocumentData,
      AllDocumentTypes,
    };
  }
}
